sudo: required
services:
  - docker
before_install:
  - docker-compose version
  - docker-compose -f resources/docker/latest/docker-compose.yml up -d
  - docker ps
install: pip install --trusted-host pypi.python.org -U tox-travis
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.8
    - python: 3.9
      dist: xenial
      sudo: true
script: tox
git:
    depth: 1
